// Generated by IcedCoffeeScript 11101.1.1
(function() {
  var key, ref, val;

  ref = require('./coffee-script');
  for (key in ref) {
    val = ref[key];
    exports[key] = val;
  }

}).call(this);
